#设置保存目录
setwd("D:/Rstudio/Rstudiostastic")
#查看当前默认保存目录
getwd()
#查看R中所包含的所有内置数据集
data(package=.packages(all.available=TRUE))
#查看state.x77数据集
state.x77
#查看热图函数如何使用
help(heatmap)
#利用内置数据集state.x77绘制热图，来查看美国50个州的8个指标之间的相关性
heatmap(state.x77)